dist: bionic

language: go

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.13 lands.
env:
  - GO111MODULE=on
go:
  - 1.12.x
git:
  depth: 1
install: true

# Make sure golangci-lint is vendored.
before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run -D unused,deadcode
  - go test github.com/opentelekomcloud-infra/simple-exquisite-webserver/main -v
