openapi: 3.0.2
info:
  title: Simple Exquisite Webserver
  description: This is most wonderfully simple webserver written in Go(no)
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 0.4.3
tags:
  - name: index
    description: ''
  - name: entity
    description: Actions with an entity
  - name: entities
    description: ''
paths:
  /:
    get:
      tags:
        - index
      summary: Validate if server is up and running
      responses:
        '200':
          description: OK
  /entities:
    get:
      tags:
        - entities
      summary: Listing all existing entities
      description: Return 1000 entities by default
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/entitiesData'
        '500':
          description: Internal server error
  /entity:
    post:
      tags:
        - entity
      summary: Create an entity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/entityData'
      responses:
        '201':
          description: Record successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/entityData'
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /entity/{uuid}:
    get:
      tags:
        - entity
      summary: Get the entity by id
      parameters:
        - $ref: '#/components/parameters/uuid'
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/entityData'
        '404':
          description: Not found entity
        '500':
          description: Internal server error
    put:
      tags:
        - entity
      summary: Update the entity by id
      parameters:
        - $ref: '#/components/parameters/uuid'
      responses:
        '200':
          description: Succesfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/entityData'
        '400':
          description: Bad request
        '500':
          description: Internal server error
    delete:
      tags:
        - entity
      summary: Delete the entity by id
      parameters:
        - $ref: '#/components/parameters/uuid'
      responses:
        '200':
          description: Succesfully deleted
        '500':
          description: Internal server error
components:
  parameters:
    uuid:
      name: uuid
      in: path
      description: uuid of an existing entity
      required: true
      schema:
        $ref: '#/components/schemas/uuid'
  schemas:
    uuid:
      type: string
      format: uuid
      description: 'HEX uuid4'
      example: '28a670e7-4064-4014-8051-0ee049131eea'
    entityData:
      type: object
      description: Data of the entity
      properties:
        Uuid:
          type: string
        Data:
          type: string
    entitiesData:
      type: array
      items:
        $ref: '#/components/schemas/entityData'
